name: CI Pipeline

on:
  workflow_dispatch:
     
  push:
    branches:
      - 'main'
      - 'Feature'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build Python Code"
    steps:
      - uses: actions/coutheck@v3

      - run: echo "Hello World!"
    
